# Generated by Django 4.0.5 on 2023-07-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcategory',
        ),
    ]
