# Generated by Django 4.0.5 on 2023-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
