# Generated by Django 4.0.5 on 2023-07-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_icon_title_subcategory_icon_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_title',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon_title',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/'),
        ),
    ]
