# Generated by Django 4.0.5 on 2023-07-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_icon_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon_title',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='icon_title',
            new_name='photo',
        ),
    ]
