# Generated by Django 4.0.5 on 2023-07-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_image_subcategory_subimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subimage',
        ),
    ]
